#!/bin/bash
USERNAME=$( echo "show State:/Users/ConsoleUser" | /usr/sbin/scutil | /usr/bin/awk '/Name :/ && ! /loginwindow/ { print $3 }' )
plist=$HOME'/Library/Application\ Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.FavoriteServers.sfl2'
rm -rf $plist

#Contents of plist file com.apple.LSSharedFileList.FavoriteServers.sfl2
cat > /Users/$USERNAME/Library/Application\ Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.FavoriteServers.sfl2 << 'ENDSCRIPT'

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$archiver</key>
	<string>NSKeyedArchiver</string>
	<key>$objects</key>
	<array>
		<string>$null</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>2</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>3</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>4</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>47</integer>
				</dict>
			</array>
		</dict>
		<string>items</string>
		<string>properties</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>5</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>19</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>25</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>30</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>35</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>6</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>7</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>8</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>9</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>10</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>11</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>16</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>17</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>18</integer>
				</dict>
			</array>
		</dict>
		<string>visibility</string>
		<string>CustomItemProperties</string>
		<string>Name</string>
		<string>Bookmark</string>
		<string>uuid</string>
		<integer>0</integer>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>13</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<string>com.apple.LSSharedFileList.OverrideIcon.OSType</string>
		<string>srvr</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSDictionary</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSDictionary</string>
		</dict>
		<string>smb://public-volume.intranet.saksroot.saksinc.com/</string>
		<data>
		Ym9va6gAAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAATAAAAAQAAAADAwAAAAAAIDIAAAABAQAAc21iOi8vcHVibGljLXZvbHVt
		ZS5pbnRyYW5ldC5zYWtzcm9vdC5zYWtzaW5jLmNvbS8AACQAAAD+////AQAA
		AAAAAAACAAAAAxAAABAAAAAAAAAAENAAAAQAAAAAAAAA
		</data>
		<string>0E054FE5-379E-484A-9BE9-884874306696</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>6</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>7</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>8</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>9</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>10</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>11</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>20</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>22</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>23</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>24</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>21</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<string>com.apple.LSSharedFileList.OverrideIcon.OSType</string>
		<string>smb://t49-vol3.intranet.saksroot.saksinc.com</string>
		<data>
		Ym9va6AAAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAARAAAAAQAAAADAwAAAAAAICwAAAABAQAAc21iOi8vdDQ5LXZvbDMuaW50
		cmFuZXQuc2Frc3Jvb3Quc2Frc2luYy5jb20kAAAA/v///wEAAAAAAAAAAgAA
		AAMQAAAQAAAAAAAAABDQAAAEAAAAAAAAAA==
		</data>
		<string>98F4461C-F64C-4566-B0A6-DF28DAC675E3</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>6</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>7</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>8</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>9</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>10</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>11</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>26</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>28</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>29</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>13</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<string>smb://t49-vol3.intranet.saksroot.saksinc.com/Merchpln</string>
		<data>
		Ym9va6wAAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAUAAAAAQAAAADAwAAAAAAIDUAAAABAQAAc21iOi8vdDQ5LXZvbDMuaW50
		cmFuZXQuc2Frc3Jvb3Quc2Frc2luYy5jb20vTWVyY2hwbG4AAAAkAAAA/v//
		/wEAAAAAAAAAAgAAAAMQAAAQAAAAAAAAABDQAAAEAAAAAAAAAA==
		</data>
		<string>3C064E7E-009D-4E76-ABFE-A1A4AEADA266</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>6</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>7</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>8</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>9</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>10</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>11</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>31</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>32</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>33</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>34</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>13</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<string>smb://t49-vol4.intranet.saksroot.saksinc.com</string>
		<data>
		Ym9va6AAAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAARAAAAAQAAAADAwAAAAAAICwAAAABAQAAc21iOi8vdDQ5LXZvbDQuaW50
		cmFuZXQuc2Frc3Jvb3Quc2Frc2luYy5jb20kAAAA/v///wEAAAAAAAAAAgAA
		AAMQAAAQAAAAAAAAABDQAAAEAAAAAAAAAA==
		</data>
		<string>F618D8E0-C1E4-48A5-9DDD-FC478EBD8BBF</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>6</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>7</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>8</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>9</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>10</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>11</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>36</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>38</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>39</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>40</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>37</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<string>com.apple.LSSharedFileList.OverrideIcon.OSType</string>
		<string>smb://t49-vol4.intranet.saksroot.saksinc.com/ECommerce</string>
		<data>
		Ym9va6wAAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAUAAAAAQAAAADAwAAAAAAIDYAAAABAQAAc21iOi8vdDQ5LXZvbDQuaW50
		cmFuZXQuc2Frc3Jvb3Quc2Frc2luYy5jb20vRUNvbW1lcmNlAAAkAAAA/v//
		/wEAAAAAAAAAAgAAAAMQAAAQAAAAAAAAABDQAAAEAAAAAAAAAA==
		</data>
		<string>6C8C7054-0B30-4BFB-9A71-9E40E75C7061</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>6</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>7</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>8</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>9</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>10</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>11</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>42</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>43</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>44</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>45</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>13</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<string>smb://t49-vol5.intranet.saksroot.saksinc.com</string>
		<data>
		Ym9va6AAAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAARAAAAAQAAAADAwAAAAAAICwAAAABAQAAc21iOi8vdDQ5LXZvbDUuaW50
		cmFuZXQuc2Frc3Jvb3Quc2Frc2luYy5jb20kAAAA/v///wEAAAAAAAAAAgAA
		AAMQAAAQAAAAAAAAABDQAAAEAAAAAAAAAA==
		</data>
		<string>D4C24978-ADF3-471F-AD07-E789B779D3B4</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSArray</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSArray</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>48</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>49</integer>
				</dict>
			</array>
		</dict>
		<string>com.apple.LSSharedFileList.ForceTemplateIcons</string>
		<false/>
	</array>
	<key>$top</key>
	<dict>
		<key>root</key>
		<dict>
			<key>CF$UID</key>
			<integer>1</integer>
		</dict>
	</dict>
	<key>$version</key>
	<integer>100000</integer>
</dict>
</plist>

ENDSCRIPT

chmod +x /Users/$USERNAME/Library/Application\ Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.FavoriteServers.sfl2
killall sharedfilelistd