#!/bin/bash
USERNAME=$( echo "show State:/Users/ConsoleUser" | /usr/sbin/scutil | /usr/bin/awk '/Name :/ && ! /loginwindow/ { print $3 }' )
plist=$HOME'/Users/$USERNAME/Library/Preferences/com.apple.ncprefs.plist'
rm -rf $plist
killall sighup usernoted
killall sighup NotificationCenter
sudo jamf recon

#Contents of plist file com.apple.LSSharedFileList.FavoriteServers.sfl2
cat > /Users/$USERNAME/Library/Preferences/com.apple.ncprefs.plist  << 'ENDSCRIPT'

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>apps</key>
	<array>
		<dict>
			<key>bundle-id</key>
			<string>com.apple.iCal</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>41951254</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Applications/Calendar.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
					LmFwcGxlLkNhbGVuZGFyTm90aWZpY2F0aW9u
					LkNhbE5DU2VydmljZQAAAAAD
					</data>
					<key>uuid</key>
					<string>8CF947EE-D576-41E0-B58B-C2268406A63E</string>
				</dict>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
					LmFwcGxlLkNhbGVuZGFyQWdlbnQAAAAAAw==
					</data>
					<key>uuid</key>
					<string>84C2F719-82C7-4F60-94DF-3D19064EE224</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>com.apple.FaceTime</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>41951246</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Applications/FaceTime.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADgAAAABAAAABgAAAAIAAAAcY29t
					LmFwcGxlLlRlbGVwaG9ueVV0aWxpdGllcwAA
					AAM=
					</data>
					<key>uuid</key>
					<string>C401152F-4471-410A-B24A-E6DA15589E33</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>com.apple.mail</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>41943054</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Applications/Mail.app</string>
		</dict>
		<dict>
			<key>auth</key>
			<integer>775</integer>
			<key>bundle-id</key>
			<string>com.apple.MobileSMS</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>864550926</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Applications/Messages.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
					LmFwcGxlLmltYWdlbnQAAAAAAAAD
					</data>
					<key>uuid</key>
					<string>D353A185-17B9-4E1E-80AC-D7EA30B647A6</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>263</integer>
			<key>bundle-id</key>
			<string>com.apple.reminders</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>847773718</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.reminders.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
					LmFwcGxlLnJlbWluZGQAAAAAAAAD
					</data>
					<key>uuid</key>
					<string>5180D16A-F3EE-460E-BDF8-B57EE4E6F7CB</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>com.apple.gamecenter</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>41951246</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.gamecenter.bundle</string>
		</dict>
		<dict>
			<key>auth</key>
			<integer>355</integer>
			<key>bundle-id</key>
			<string>com.apple.Home</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>2986868742</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.Home.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
					LmFwcGxlLmhvbWVkAAAAAAM=
					</data>
					<key>uuid</key>
					<string>EED8356C-8D8D-4259-AFB4-E70C96174219</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>com.apple.AppSSOKerberos.notifications</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>327163926</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.AppSSOKerberos.notifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAVY29t
					LmFwcGxlLkFwcFNTT0FnZW50AAAAAAAAAw==
					</data>
					<key>uuid</key>
					<string>E1FEA58E-B132-48D2-A28F-1C49E30DC2D6</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>323</integer>
			<key>bundle-id</key>
			<string>com.apple.findmy</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>2986344454</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Applications/FindMy.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAAEQAAAABAAAABgAAAAIAAAAlY29t
					LmFwcGxlLmljbG91ZC5zZWFyY2hwYXJ0eXVz
					ZXJhZ2VudAAAAAAAAAM=
					</data>
					<key>uuid</key>
					<string>15DAE113-E41F-4D9F-BDDA-11393D5F7F39</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>326</integer>
			<key>bundle-id</key>
			<string>com.jamf.connect</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>805314566</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/Applications/Jamf Connect.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>0</integer>
					<key>path</key>
					<string>/Applications/Jamf Connect.app</string>
					<key>req</key>
					<data>
					+t4MAAAAALwAAAABAAAABgAAAAYAAAAPAAAA
					AgAAABBjb20uamFtZi5jb25uZWN0AAAABwAA
					AA4AAAAAAAAACiqGSIb3Y2QGAQkAAAAAAAAA
					AAAGAAAABgAAAA4AAAABAAAACiqGSIb3Y2QG
					AgYAAAAAAAAAAAAOAAAAAAAAAAoqhkiG92Nk
					BgENAAAAAAAAAAAACwAAAAAAAAAKc3ViamVj
					dC5PVQAAAAAAAQAAAAo0ODNEV0tXNDQzAAA=
					</data>
					<key>uuid</key>
					<string>8ACAFA72-2BDB-42EB-AE1F-B48E0AD24C5E</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>6</integer>
			<key>bundle-id</key>
			<string>com.apple.BTUserNotifications</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>327688214</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.BTUserNotifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAAUY29t
					LmFwcGxlLmNsb3VkcGFpcmQAAAAD
					</data>
					<key>uuid</key>
					<string>338AFE92-3A98-4DBB-B669-DB33E466E7A8</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>4</integer>
			<key>bundle-id</key>
			<string>com.apple.tips</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>327680022</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.tips.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
					LmFwcGxlLnRpcHNkAAAAAAM=
					</data>
					<key>uuid</key>
					<string>686542C9-2B3D-4B3E-B522-0F47258CB380</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>com.crowdstrike.falcon.UserAgent</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>268443662</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/Applications/Falcon.app/Contents/Library/LaunchServices/Falcon Notifications.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>0</integer>
					<key>path</key>
					<string>/Applications/Falcon.app/Contents/Library/LaunchServices/Falcon Notifications.app</string>
					<key>req</key>
					<data>
					+t4MAAAAAKwAAAABAAAABgAAAAIAAAAgY29t
					LmNyb3dkc3RyaWtlLmZhbGNvbi5Vc2VyQWdl
					bnQAAAAGAAAADwAAAAYAAAAOAAAAAQAAAAoq
					hkiG92NkBgIGAAAAAAAAAAAABgAAAA4AAAAA
					AAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAA
					AAAAAApzdWJqZWN0Lk9VAAAAAAABAAAAClg5
					RTk1NlA0NDYAAA==
					</data>
					<key>uuid</key>
					<string>49C91D47-D115-4526-83A2-AB4279A8E144</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>com.jamfsoftware.Management-Action</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>8206</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/Library/Application Support/JAMF/bin/Management Action.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>0</integer>
					<key>path</key>
					<string>/Library/Application Support/JAMF/bin/Management Action.app</string>
					<key>req</key>
					<data>
					+t4MAAAAANAAAAABAAAABgAAAAYAAAAPAAAA
					AgAAACJjb20uamFtZnNvZnR3YXJlLk1hbmFn
					ZW1lbnQtQWN0aW9uAAAAAAAHAAAADgAAAAAA
					AAAKKoZIhvdjZAYBCQAAAAAAAAAAAAYAAAAG
					AAAADgAAAAEAAAAKKoZIhvdjZAYCBgAAAAAA
					AAAAAA4AAAAAAAAACiqGSIb3Y2QGAQ0AAAAA
					AAAAAAALAAAAAAAAAApzdWJqZWN0Lk9VAAAA
					AAABAAAACjQ4M0RXS1c0NDMAAA==
					</data>
					<key>uuid</key>
					<string>5D62EF21-29E8-4CE9-800C-08EDAE73D661</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>us.zoom.xos</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>310386702</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/Applications/zoom.us.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>0</integer>
					<key>path</key>
					<string>/Applications/zoom.us.app</string>
					<key>req</key>
					<data>
					+t4MAAAAAJgAAAABAAAABgAAAAIAAAALdXMu
					em9vbS54b3MAAAAABgAAAA8AAAAGAAAADgAA
					AAEAAAAKKoZIhvdjZAYCBgAAAAAAAAAAAAYA
					AAAOAAAAAAAAAAoqhkiG92NkBgENAAAAAAAA
					AAAACwAAAAAAAAAKc3ViamVjdC5PVQAAAAAA
					AQAAAApCSjRIQUFCOUIzAAA=
					</data>
					<key>uuid</key>
					<string>2C3F21DF-0E08-4B0F-8627-297632784F0C</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>327</integer>
			<key>bundle-id</key>
			<string>com.apple.Passbook</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>2986868742</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.Passbook.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
					LmFwcGxlLnBhc3NkAAAAAAM=
					</data>
					<key>uuid</key>
					<string>ACE809F2-0E13-4C87-95DA-8FA7D999D2C6</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>com.jamfsoftware.selfservice.mac</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>8206</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/Applications/Self Service.app</string>
			<key>push</key>
			<dict>
				<key>env</key>
				<string>production</string>
				<key>token</key>
				<data>
				</data>
				<key>topic</key>
				<string>com.jamfsoftware.selfservice.mac</string>
				<key>types</key>
				<integer>5</integer>
			</dict>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>com.google.Chrome.framework.AlertNotificationService</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>41951254</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/108.0.5359.124/Helpers/Google Chrome Helper (Alerts).app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>0</integer>
					<key>path</key>
					<string>/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/108.0.5359.124/Helpers/Google Chrome Helper (Alerts).app</string>
					<key>req</key>
					<data>
					+t4MAAAAAMAAAAABAAAABgAAAAYAAAAGAAAA
					BgAAAAIAAAA0Y29tLmdvb2dsZS5DaHJvbWUu
					ZnJhbWV3b3JrLkFsZXJ0Tm90aWZpY2F0aW9u
					U2VydmljZQAAAA8AAAAOAAAAAQAAAAoqhkiG
					92NkBgIGAAAAAAAAAAAADgAAAAAAAAAKKoZI
					hvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAACnN1
					YmplY3QuT1UAAAAAAAEAAAAKRVFIWFo4TThB
					VgAA
					</data>
					<key>uuid</key>
					<string>30B1F923-BFE8-4773-AC11-210DBEB30BD5</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>com.google.Chrome</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>8206</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/Applications/Google Chrome.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>0</integer>
					<key>path</key>
					<string>/Applications/Google Chrome.app</string>
					<key>req</key>
					<data>
					+t4MAAAAAQwAAAABAAAABgAAAAYAAAAGAAAA
					BgAAAAcAAAAHAAAABwAAAAIAAAARY29tLmdv
					b2dsZS5DaHJvbWUAAAAAAAACAAAAFmNvbS5n
					b29nbGUuQ2hyb21lLmJldGEAAAAAAAIAAAAV
					Y29tLmdvb2dsZS5DaHJvbWUuZGV2AAAAAAAA
					AgAAABhjb20uZ29vZ2xlLkNocm9tZS5jYW5h
					cnkAAAAPAAAADgAAAAEAAAAKKoZIhvdjZAYC
					BgAAAAAAAAAAAA4AAAAAAAAACiqGSIb3Y2QG
					AQ0AAAAAAAAAAAALAAAAAAAAAApzdWJqZWN0
					Lk9VAAAAAAABAAAACkVRSFhaOE04QVYAAA==
					</data>
					<key>uuid</key>
					<string>D852BC50-EE35-47F6-8304-EEC7FF05D455</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>com.tinyspeck.slackmacgap</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>41951310</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/Applications/Slack.app</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>0</integer>
					<key>path</key>
					<string>/Applications/Slack.app</string>
					<key>req</key>
					<data>
					+t4MAAAAAKgAAAABAAAABgAAAAIAAAAZY29t
					LnRpbnlzcGVjay5zbGFja21hY2dhcAAAAAAA
					AAYAAAAPAAAABgAAAA4AAAABAAAACiqGSIb3
					Y2QGAgYAAAAAAAAAAAAGAAAADgAAAAAAAAAK
					KoZIhvdjZAYBDQAAAAAAAAAAAAsAAAAAAAAA
					CnN1YmplY3QuT1UAAAAAAAEAAAAKQlFSODJS
					QkJITAAA
					</data>
					<key>uuid</key>
					<string>CE4024A9-CE2F-490B-8E1C-2B006956B9A1</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.followup.alert</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943703</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
					LmFwcGxlLmZvbGxvd3VwZAAAAAAD
					</data>
					<key>uuid</key>
					<string>5CF36C89-449F-4BDB-AC1F-813EF4FDC408</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>4</integer>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.wifi.usernotifications.diagnostics</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>327680662</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
					LmFwcGxlLndpZmkuV2lGaUFnZW50AAAAAw==
					</data>
					<key>uuid</key>
					<string>72EE7551-B14C-45D7-9DAF-B5CDBE9258AD</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.CalendarNotification.CalNCService</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
					LmFwcGxlLkNhbGVuZGFyTm90aWZpY2F0aW9u
					LkNhbE5DU2VydmljZQAAAAAD
					</data>
					<key>uuid</key>
					<string>7A439390-DBD2-4D27-8B57-0B7C07EE4162</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.sharingd</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
					LmFwcGxlLnNoYXJpbmdkAAAAAAAD
					</data>
					<key>uuid</key>
					<string>9043C543-7A80-49DA-87B7-E0E9B692928A</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.FaceTime</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADgAAAABAAAABgAAAAIAAAAcY29t
					LmFwcGxlLlRlbGVwaG9ueVV0aWxpdGllcwAA
					AAM=
					</data>
					<key>uuid</key>
					<string>9845CBA9-E6BF-4899-A2B1-3291FA14BF91</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.appstoreagent</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.TMHelperAgent</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.mdmclient</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
					LmFwcGxlLm1kbWNsaWVudAAAAAAD
					</data>
					<key>uuid</key>
					<string>DD3CAB29-86B1-4FED-8316-337E80C33CBE</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>263</integer>
			<key>bundle-id</key>
			<string>com.apple.AppleMediaServicesUI.engagement.notifications</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>864551062</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.AppleMediaServicesUI.engagement.notifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
					LmFwcGxlLmFtc2VuZ2FnZW1lbnRkAAAAAw==
					</data>
					<key>uuid</key>
					<string>33705999-381B-4814-8E9C-EE282B444D1E</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>6</integer>
			<key>bundle-id</key>
			<string>com.apple.ScreenTimeEnabledNotifications</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>4622647444</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.ScreenTimeEnabledNotifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADgAAAABAAAABgAAAAIAAAAZY29t
					LmFwcGxlLlNjcmVlblRpbWVBZ2VudAAAAAAA
					AAM=
					</data>
					<key>uuid</key>
					<string>C89487C3-FFDC-42C0-9723-54053488A64C</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>com.apple.mdmclient.usernotifications.v2</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>327688342</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.mdmclient.usernotifications.v2.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
					LmFwcGxlLm1kbWNsaWVudAAAAAAD
					</data>
					<key>uuid</key>
					<string>35EDE226-61C4-4DBE-A5BD-C29FD7894B38</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>com.apple.iChat</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>41943054</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADgAAAABAAAABgAAAAIAAAAbY29t
					LmFwcGxlLmlkZW50aXR5c2VydmljZXNkAAAA
					AAM=
					</data>
					<key>uuid</key>
					<string>785CBDC8-2663-444A-92C0-64422451C799</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.SoftwareUpdateNotification</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>327688855</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
					LmFwcGxlLlNvZnR3YXJlVXBkYXRlTm90aWZp
					Y2F0aW9uTWFuYWdlcgAAAAAD
					</data>
					<key>uuid</key>
					<string>C174A90C-8B79-401E-B01D-7947DF24BB5C</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>6</integer>
			<key>bundle-id</key>
			<string>com.apple.notificationcenter.askpermissions</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>310383127</integer>
			<key>grouping</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.security.keychain-circle-notification</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAAEwAAAABAAAABgAAAAIAAAAvY29t
					LmFwcGxlLnNlY3VyaXR5LktleWNoYWluLUNp
					cmNsZS1Ob3RpZmljYXRpb24AAAAAAw==
					</data>
					<key>uuid</key>
					<string>9EB1D217-A65F-44F8-A6E4-C4CB6871060E</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>com.apple.controlcenter.notifications.low-battery</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>327688342</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.controlcenter.notifications.low-battery.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
					LmFwcGxlLmNvbnRyb2xjZW50ZXIAAAAAAw==
					</data>
					<key>uuid</key>
					<string>BF6A50F6-E32F-4203-8744-968D71CC6656</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>262</integer>
			<key>bundle-id</key>
			<string>com.apple.ScreenTimeNotifications</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>5100797964</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.ScreenTimeNotifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADgAAAABAAAABgAAAAIAAAAZY29t
					LmFwcGxlLlNjcmVlblRpbWVBZ2VudAAAAAAA
					AAM=
					</data>
					<key>uuid</key>
					<string>8752D0EB-54AD-4DE9-A557-98BB299A7E7C</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>7</integer>
			<key>bundle-id</key>
			<string>com.apple.appleaccount.notifications</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>327680142</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.appleaccount.notifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
					LmFwcGxlLmFwcGxlYWNjb3VudGQAAAAAAw==
					</data>
					<key>uuid</key>
					<string>A496C1DD-9611-4464-8DED-F14CC2B2F5C7</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>6</integer>
			<key>bundle-id</key>
			<string>com.apple.studentd.notifications</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>327688342</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.studentd.notifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
					LmFwcGxlLnN0dWRlbnRkAAAAAAAD
					</data>
					<key>uuid</key>
					<string>B9F2240B-6C6B-417C-A9B8-417CBF3761C7</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.sharingd.continuity</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
					LmFwcGxlLnNoYXJpbmdkAAAAAAAD
					</data>
					<key>uuid</key>
					<string>A7675B2C-550B-4083-A828-63A0EB7E4312</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>4</integer>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.wifi.usernotifications.autohotspot</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>327680662</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
					LmFwcGxlLndpZmkuV2lGaUFnZW50AAAAAw==
					</data>
					<key>uuid</key>
					<string>98ACC3E4-6EB8-4613-A940-BD26749BF958</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>4</integer>
			<key>bundle-id</key>
			<string>com.apple.ReplayKitNotifications</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>327688334</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.ReplayKitNotifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
					LmFwcGxlLnJlcGxheWQAAAAAAAAD
					</data>
					<key>uuid</key>
					<string>148E03D5-EAD5-4821-9528-849B8B998BDB</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>auth</key>
			<integer>263</integer>
			<key>bundle-id</key>
			<string>com.apple.askpermission.notifications</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>864551062</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.askpermission.notifications.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
					LmFwcGxlLmFza3Blcm1pc3Npb25kAAAAAw==
					</data>
					<key>uuid</key>
					<string>9E6C31DB-7D9C-4292-90DB-66BE43F47906</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.MobileAccessoryUpdater.fudHelperAgent</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
					LmFwcGxlLmZ1ZEhlbHBlckFnZW50AAAAAw==
					</data>
					<key>uuid</key>
					<string>1CAFFAD7-5868-4894-904C-AE2C17843C71</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.migrationhelper</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.storeassetd</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.accountsd</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>auth</key>
			<integer>261</integer>
			<key>bundle-id</key>
			<string>com.apple.AppStore</string>
			<key>content_visibility</key>
			<integer>0</integer>
			<key>flags</key>
			<integer>805830674</integer>
			<key>grouping</key>
			<integer>0</integer>
			<key>path</key>
			<string>/System/Library/UserNotifications/Bundles/com.apple.AppStore.bundle</string>
			<key>src</key>
			<array>
				<dict>
					<key>flags</key>
					<integer>6</integer>
					<key>req</key>
					<data>
					+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
					LmFwcGxlLmFwcHN0b3JlYWdlbnQAAAAAAw==
					</data>
					<key>uuid</key>
					<string>CFF1CDBD-40C1-41C6-8AC1-7488743AAEEE</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.BluetoothUIServer</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>bundle-id</key>
			<string>_SYSTEM_CENTER_:com.apple.askpermissiond</string>
			<key>content_visibility</key>
			<integer>3</integer>
			<key>flags</key>
			<integer>41943575</integer>
			<key>grouping</key>
			<integer>0</integer>
		</dict>
	</array>
	<key>content_visibility</key>
	<integer>2</integer>
	<key>dnd_prefs</key>
	<data>
	YnBsaXN0MDDVAQIDBAUGBggICFtkbmRNaXJyb3JlZF8QD2RuZERpc3BsYXlTbGVlcF8Q
	HnJlcGVhdGVkRmFjZXRpbWVDYWxsc0JyZWFrc0RORF5kbmREaXNwbGF5TG9ja18QE2Zh
	Y2V0aW1lQ2FuQnJlYWtETkQJCQgICAgTHzFSYXd4eXp7AAAAAAAAAQEAAAAAAAAACwAA
	AAAAAAAAAAAAAAAAAHw=
	</data>
	<key>sort_order</key>
	<integer>0</integer>
	<key>version</key>
	<integer>1</integer>
</dict>
</plist>

ENDSCRIPT

chmod +x /Users/$USERNAME/Library/Preferences/com.apple.ncprefs.plist
killall sighup usernoted
killall sighup NotificationCenter